### ISSUE TITLE
デモ動画の作成

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#101]
# 概要・目的
提出に必要なため、デモ動画を作成する。

# AsIs
デモ動画がない

# ToBe
デモ動画がある

# タスク

**Comment by hoosan** [comment]
@bioerrorlog @ClankPan 

作りましたのでご確認ください🙏
https://user-images.githubusercontent.com/40290137/174461118-1a816e3f-f5e3-4f72-b988-e9da30d5c037.mp4

**Comment by hoosan** [comment]
@bioerrorlog @ClankPan 
モバイルだとうまく表示できなかったのでYouTubeアップロードしました
https://youtu.be/cvMM_Ng7kWg

**Comment by bioerrorlog** [comment]
@hoosan 
すごい！
良いと思います！！
