### ISSUE TITLE
ログイン時にバックエンドにユーザーの情報を登録する

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#14]
# 概要・目的
ログイン時にバックエンドにユーザーの情報を登録する

# AsIs
ログイン時にバックエンドにユーザー情報が登録されない

# ToBe
ログイン時にバックエンドにユーザー情報が登録される

# タスク
- [x] バックエンドにユーザー Model （`User`）を追加（取り急ぎユーザー名のみ）
- [x] NFTBarter canister に ユーザー情報を持たせる `user` HashMapを追加
- [x] ログイン時にユーザーを登録する `register` メソッドを追加
- [x] `msg.caller` で `user` を探索しユーザー情報を取得する `getUserInfo` メソッドを追加
- [x]  フロントエンドから `register` メソッドを呼び出し
- [x] フロントエンドから `getUserInfo` メソッドを呼び出し
- [x] e2e テストを追加

**Comment by ClankPan** [comment]
@hoosan 
この部分私が書いてもいいでしょうか？

**Comment by hoosan** [comment]
@ClankPan すみません、バックエンド部分書いちゃったので、今からPR出しますのでレビューいただけると大変ありがたいです！！
