### ISSUE TITLE
ユーザー名を変更する機能の開発（バックエンド）

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#19]
# 概要・目的
ユーザー名を変更する機能の開発（バックエンド側）

# AsIs
ユーザー名を変更するメソッドがない

# ToBe
`NFTBarter` が `updateUserName` 関数を持つ。
ユーザー名を`Text`引数で渡して、`msg.caller`をキーに`user`を探索して該当ユーザーの`name`変数を上書きする。
`updateUserName` の返し値は変更後のユーザー情報とする(`User.freeze()`でイミュータブルに変換して返す)

# タスク
- [ ] `updateUserName` 関数の実装
- [ ] `dfx canister call` による動作確認

**Comment by hoosan** [comment]
@ClankPan #18 が閉じましたらこちらのIssue取って頂くのはどうでしょう？

**Comment by hoosan** [comment]
#18 で`name` fieldを残すか要議論

**Comment by ClankPan** [comment]
フロントとのインターフェースはそのままで，ユーザーやキャニスターを管理する情報はclassへまとめて，mainではアクセス管理のみを記述したいですね．

**Comment by hoosan** [comment]
#18 で `name` fieldを省略する方針になったためクローズします
