### ISSUE TITLE
Add tests for mintChildCanister

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/nft-barter#28]
# 概要・目的
Canisterのpublic func: `mintChildCanister`のe2eテストを追加する

# AsIs
`mintChildCanister`の振る舞いがテストで保障されていない。

# ToBe
`mintChildCanister`の振る舞いがテストで保障されている。

# タスク

**Comment by hoosan** [comment]
#77 のついでに実装します
