### ISSUE TITLE
jazzicon の Security Alert 対応

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#38]
# 概要・目的
jazziconが仕様しているcolor-string@^0.3.0にセキュリティアラートが上がっている
https://github.com/Japan-DfinityInfoHub/nft-barter/security/dependabot/1

# AsIs
color-stringのバージョンが0.3.0

# ToBe
color-stringのバージョンが1.5.5以上

# タスク
すでにPRが出ているのでこれがマージされ次第アップデートする
https://github.com/MetaMask/jazzicon/pull/7

**Comment by bioerrorlog** [comment]
アラート内容的に現プロジェクトには関係のないリスクのため、dismiss済み。
