### ISSUE TITLE
ResultのErrorをTextではなくvariantで返す

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/nft-barter#50]
# 概要・目的
現状はcanister call結果のResultはerr時にTextが格納されている。
TextよりもError variant型の方がハンドルしやすいので、変更したい。

# AsIs
canister call結果がerrの場合、Textが返される

# ToBe
canister call結果がerrの場合、Error variant型が返される

# タスク
- [x] Error variantを定義
- [x] canister public funcのResultをerr時Textからerr時Error variantに変更
- [x] e2e testを更新

**Comment by hoosan** [comment]
@bioerrorlog 
Error variant 定義の方針として、そのメソッド特有のものは `#other` に、そうでなければ variant に適切に定義と考えているのですが、現状ですと複数のメソッドにまたがっているのは anonymous principal を弾く時くらいなので、

```
  public type Error = {
    #unauthorized : Principal;
    #other : Text;
  }
```

で良いでしょうか？

なお、テストでは エラーメッセージまではtoStrictEqualでチェックしなくても良いと思っております。
例えば、以下のイメージです。
```
    expect(res).toEqual({
      err: {
        other: expect.anything(),
      },
    });
```

ご意見あればお願いします🙏

**Comment by bioerrorlog** [comment]
@hoosan 
> テストでは エラーメッセージまではtoStrictEqualでチェックしなくても良いと思っております。

賛成です！
テストではError Typeまでの保証に留めて良いと思います(エラーメッセージの変更はリファクタの範疇としておく)。

> Error variant 定義の方針として、そのメソッド特有のものは #other に、そうでなければ variant に適切に定義

個人的には、現時点ではメソッド特有であっても、主張したいエラーの趣旨が割と明らかなのでvariantにしてしまってよい気がしましたがどうでしょうか。(今後増えるfunctionやChildCanisterの実装でerrorの独自定義を防ぐ)
例えば下記のようなイメージです
```
  public type Error = {
    #unauthorized : Principal; // or Text..?
    #notYetRegistered : Text;
    #alreadyRegistered : Text;
  }
```

**Comment by bioerrorlog** [comment]
(ちなみに、Error messegeとkindを分けてしまうのも責務が明確で良いかなと思いましたが、今回はEXT側の実装と揃えて上記の形で良いと思います！)
```
  public type TransferError = {
    message : ?Text;
    kind : {
      #BadFee;
      #InsufficientFunds;
      #InvalidToken;
      #InvalidDestination;
      #Other;
    };
  };
```
https://github.com/dfinity/invoice-canister/blob/f5243c63e1226805373911420088d3ab00dd1e26/src/invoice/Types.mo#L171-L180
