### ISSUE TITLE
NFTミントの上限設定についての仕様決定

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#59]
# 概要・目的
NFTミントの上限設定についての仕様を決定する

# AsIs
NFTミントの上限設定についての仕様が決まっていない

# ToBe
NFTミントの上限設定についての仕様が決まっている

# タスク

**Comment by hoosan** [comment]
@bioerrorlog @ClankPan 
現状特に制限つけずに実装進めているのですが、ユーザーごと最大値（例えば10とか？）を設定した方が良いでしょうか。

**Comment by bioerrorlog** [comment]
自分は上限設けなくても良いのでは、と思ってしまいました。

悪意のない人がポチポチmintするのには別に上限を設けなくても良いと思いますし、逆に悪意ある人がいたずら/大量mintするような場合はユーザごとのmint上限を設けても防げないかなと。

**Comment by hoosan** [comment]
コメントありがとうございます！ご意見その通りかと思います🙌それでは上限は設けないということでクローズさせていただきます🙏
