### ISSUE TITLE
NFTを出品する際のユーザーフローの仕様を決める

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#72]
# 概要・目的
NFTを出品する際のユーザーフローの仕様を決める

## 仕様案
- プロフィール画面のNFTカードに~~`Exchange`~~ `Exhibit` ボタンを追加し、ユーザーはプロフィール画面で交換に出したいNFTのボタンをクリックする
- ポップアップが表示され、本当に交換に出すかの確認画面が出る。ユーザーはYES/NO選択。
- `childCanister`がなければ、新たにCanisterを作成する必要があるのでその旨が表示される。Canister生成のための支払い（1 ICP？）を行う。（Plugと繋げて支払いを促す）
- `childCanister`ではNFTをimportする`importMyNft`メソッドとNFTを出品状態にする`exhibitMyNf`を立て続けにコールする
参考：https://github.com/Japan-DfinityInfoHub/nft-barter/pull/73
- 待ち時間が生じるのでローディング画面を表示する
- 完了を示す画面が表示される。

# AsIs
NFTを交換に出した時のユーザーフローが曖昧

# ToBe
NFTを交換に出した時のユーザーフローが決まる

# タスク

**Comment by hoosan** [comment]
@bioerrorlog @ClankPan 
仕様案作りましたので確認お願いします

**Comment by ClankPan** [comment]
> プロフィール画面のNFTカードにExchangeボタンを追加し、ユーザーはプロフィール画面で交換に出したいNFTのボタンをクリックする
これって，出品者側のことでしょうか？

**Comment by hoosan** [comment]
はい、出品者がわのユーザーフローです🙏

**Comment by ClankPan** [comment]
出品：`Exhibit`，入札：`Bid`とかですかね？

**Comment by hoosan** [comment]
Exhibit 出展感が強いなと思ってましたがまぁあるいみ展示でもあるかと思い直しました。ありがとうございます！Exhibitでいきます🙏

**Comment by ClankPan** [comment]
> childCanisterがなければ、新たにCanisterを作成する必要があるのでその旨が表示される。

あとここなんですが，NFTがimportされているなら必ずchildcanisterは生成されているかと！
もしかしたら，この辺り食い違いがあるかもしれません...

**Comment by ClankPan** [comment]
@hoosan 
なるほど，`プロフィール画面で表示されているNFT`はすでにchildcanisterが取り込んでいるNFTではなく，plugなどのwallet上に存在するNFTのことなんですね．
それでしたら，僕の認識と問題はないです！

**Comment by bioerrorlog** [comment]
自分はこのユーザーフローで違和感ありません！
(ひとつあるとすれば、Canister生成のための支払いを出品者に要求する、をこのデモ段階でも入れるのか?は少し思いました.)

**Comment by hoosan** [comment]
> (ひとつあるとすれば、Canister生成のための支払いを出品者に要求する、をこのデモ段階でも入れるのか?は少し思いました.)
@bioerrorlog はい、私もそこは同じように思っていまして、ひとまずPlug経由支払いはなしで実装進めるのが良いと思います。

@ClankPan 
PR拝見したところ、やはりユーザーフローに認識ずれがあるような気がしました🙏

こちらのissueはまだ閉じずにおきます！

**Comment by hoosan** [comment]
https://github.com/Japan-DfinityInfoHub/nft-barter/pull/73
こちらのPRで認識すり合わせした以下の結果を反映し、本Issueはクローズします！
- `childCanister`ではNFTをimportする`importMyNft`メソッドとNFTを出品状態にする`exhibitMyNf`を立て続けにコールする
