### ISSUE TITLE
入札処理の追加

### ISSUE THREAD

**Issue by ClankPan** [Japan-DfinityInfoHub/nft-barter#75]
# 概要・目的
入札処理を追加する．

# AsIs
出品処理のみで，入札処理がない．

# ToBe
入札者は自身のChildCanisterへNFTをimportし，他のChildCanisterが持つExhibit NFTへBidする．

# タスク
ChildCanisterが実装すべきメソッド
- offerBid 
- acceptOffer
- sendToMe

mainが実装すべきメソッド
- isBrother

**Comment by hoosan** [comment]
@ClankPan 
明日の会話の前に、疑問点をいくつか書いておきます。

1. _assets、_assetOwners, _auctionsのHashMapのキーはtokenIndexではなくTokenIdentifierが良いのではないでしょうか。どのTokenIndexとTokenIdentifierが対応しているのかassetsにいちいち問い合わせないとわからないため。

2. offerBidMyNftのコールの流れは複雑なので、Aliceが出品者、Bobが入札者と考えます。

 (i) BobからAliceに入札するとき、BobはBobの持つChildCanister（以下BobCC）のofferBidMyNftにコールする
このときofferBidMyNftのcallerはBob

(ii) BobCCのofferBidMyNftメソッドが呼ばれ、このメソッド内でAliceCCのacceptOffer（acceptBitOfferの間違い？）をコールする
このときacceptBitOfferのcallerはBobCC

(iii) AliceCCのacceptBitOfferメソッドが呼ばれ、このメソッド内でBobCCのsendToMeメソッドをコールする
このときsendToMeのcallerは AliceCC

(iv) BobCCのsendToMeが呼ばれる。
caller はAliceCC なので、#OKのcallerの中にはAliceCCが入る
→ AliceCCで呼ばれたacceptBitOffer内でownerとして使われるので、owner = AliceCCになる。

という流れになるかと思います。ただ、これだと、AliceCCで呼ばれたacceptBitOffer内で
```
_assetOwners.put(tokenIndex, owner);
```
をすると、tokenIndexのownerがAliceCCになってしまうと思うのですが、これは正しい挙動でしょうか？
（Bobがbidしているので、BobCCがownerになるのが正しいように思うのですが）

**Comment by hoosan** [comment]
FYI: @bioerrorlog 

@ClankPan さんと会話したメモを置いておきます

## 現在の実装についての疑問点の解消

> _assets、_assetOwners, _auctionsのHashMapのキーはtokenIndexではなくTokenIdentifierが良いのではないでしょうか。

TokenIdentifierはEXT規格のみであるため、汎用的にするにはTokenIndexとするのが良い。
結論：キーはTokenIndexのままとする

> tokenIndexのownerがAliceCCになってしまうと思うのですが、これは正しい挙動でしょうか？

要修正：上の場合、ownerがBobCCになるようにする


## 追加で必要な実装

1. CCに`select()` メソッドを生やし、これをAliceが叩くことでbidされているNFTのうち一つを選択することを可能にする。`select` では、NFTのStatusを変更する。
- もともと`#Exhibit`だったものは`#ExhibitEnd`に変更
- `#Bid`だったものは、交換対象として選択されれば`#Selected`に、選択されなければ`#NotSelected` に変更する。

2. それぞれのCCに、NFTを引き出すメソッドを実装する。（CC間での引き出しと、自分のCCからひきだすメソッドの2つが必要）
BobがBidしたNFTあるいは交換が成立したNFTを引き出したいときは、AliceCC -> BobCC -> Bobのルートでtransferを行う必要がある


## その他注意点

`assert` している部分は、Status変更をロールバックしたい場合か、assertの実行が起こり得ないと考える場所である。
-> 必要に応じてコメントを追加する

## 今後の進め方

@hoosan が既存コードをベースに実装し @ClankPan にレビューいただく（明日目処）
