### ISSUE TITLE
出品済みのNFTに対して入札（Bid）する際のユーザーフローの仕様を決める

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#83]
# 概要・目的
出品済みのNFTに対して入札（Bid）する際のユーザーフローの仕様を決める

## 仕様案
- 出品済みのNFTは詳細ページに「Place Exchange Offer」のボタンが現れる
※ デザインイメージ（Exchange offer ending inの表示はデモには含めない）
![image](https://user-images.githubusercontent.com/40290137/172053269-c6b668e8-7891-4d03-99e5-22bbdbec426a.png)
- ボタンを押すと自分のウォレット内のNFT一覧が表示される画面になる。
※デザインイメージ
![image](https://user-images.githubusercontent.com/40290137/172361961-2fdf48b7-855b-4317-af2d-ae54c48b4b65.png)

- NFTを選択するとポップアップが表示され、本当に入札するかの確認画面が出る（出品時と同様）。 
- YESを押すとBidが行われるまでの間ローディング画面を表示する（出品時と同様）。
- 入札が行われるとNFTのステータスが「Bid」に変わる

# AsIs
入札のユーザーフローが曖昧

# ToBe
入札のユーザーフローが決まる

# タスク

**Comment by hoosan** [comment]
@bioerrorlog @ClankPan 仕様案作りましたのでご確認お願いします🙏

**Comment by bioerrorlog** [comment]
良いと思います!

> Exchange offer ending inの表示はデモには含めない

このスコープも賛成です。

**Comment by hoosan** [comment]
@ClankPan どうでしょう？イメージ合いますか？

**Comment by hoosan** [comment]
認識同期できましたのでクローズします🙏
