### ISSUE TITLE
説明用 Canister アーキテクチャの作図

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/nft-barter#87]
# 概要・目的
Canister アーキテクチャを説明する図を作成する
（提出用デモ動画とREADMEに使用する）

## 図案
https://excalidraw.com/#json=eFGh97IkI394CXv8Pq4Hq,nyWQwT61r3Q7EdvkR95nQA

(1) UserごとにChild Canister があることを示す図
![image](https://user-images.githubusercontent.com/40290137/172853327-74e95e35-6dce-4eb2-ad95-16195ab0ad6c.png)

(2) 出品の際には Alice の Wallet から Alice の Child Canister に NFTが送られることを示す図
![image](https://user-images.githubusercontent.com/40290137/172853497-20dddbd8-b041-40c0-9188-91af1b99f36e.png)

(3)  入札の際には各ユーザのNFTがWalletから各自のChild Canister に送られることを示す図
![image](https://user-images.githubusercontent.com/40290137/172853617-90a386b5-d567-4064-8d2e-9895d8113b17.png)

(4) 入札されたNFTは最終的にAliceのChild Canisterに送られ、statusとassetOwnerが紐づくことを示す図
![image](https://user-images.githubusercontent.com/40290137/172853838-c78ea304-f8ab-42a6-ac8b-3308d1049dc7.png)

(5) NFT の交換は Child Canister 上でassetOwnerが入れ替わることで実施されることを示す図
![image](https://user-images.githubusercontent.com/40290137/172853876-ad8c159e-da81-4fbc-9745-7452faaa1992.png)

# AsIs
Canister アーキテクチャについての説明がされていない

# ToBe
Canister アーキテクチャについての説明がなされている
デモ動画やリポジトリを見る人の理解の役に立つような図がある

# タスク

**Comment by hoosan** [comment]
@bioerrorlog ご確認お願いします
@ClankPan  Child Canister 間でのNFT交換ということで認識合っているかご確認お願いします

**Comment by bioerrorlog** [comment]
(1)~(2)はイメージ合います！

(3)~(4)は私のイメージとは少し違いました。
(ここでBobのchild canisterが役割を持つんでしたっけ..?)

この辺りは @ClankPan さんが実装中でしょうか？

**Comment by hoosan** [comment]
@bioerrorlog すみません、コードの読み込みが不十分で図解間違ってました。
(3)については図が不十分で、一度各自（BobとCharlie）のChild CanisterにNFTを送った後、さらにAliceのChildCanisterに送られます。（NFTのownerがAliceのChild Canisterになるが、Alice のChild Canister内部のassetOwner変数のownerにBobとCharlieのChildCanisterのCanisterIDが保存される状態になる）

(4)は完全に間違いで、NFTの交換はAliceのChild Canister内で行われます

**Comment by bioerrorlog** [comment]
ありがとうございます！
イメージ合います！

**Comment by hoosan** [comment]
こちらクローズします✅
